export const styles = {
  body: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
  },
  topBar: {
    backgroundColor: "rgb(235, 235, 235)",
    display: "flex",
    width: "100%",
    height: "150px",
    margin: "0px",
    textAlign: "left",
    alignItems: "center",
    color: "black",
    borderRadius: "0%",
    position: "relative",
  },
  topBarButton: {
    marginLeft: "20px",
    color: "black",
    fontWeight: "bold",
    fontSize: "25px",
    fontFamily: "Oswald, sans-serif",
    "&:hover": {
      color: "rgb(130, 130, 130)",
      backgroundColor: "rgb(235, 235, 235)",
      // border: "2px solid rgb(130, 130, 130)"
    },
  },
  topBarButtonContainer: {
    position: "absolute",
    display: "flex",
    flexDirection: "row",
    margin: "10px",
    bottom: "5px",
    right: "5px",
  },
  bottomContainer: {
    width: "100%",
    height: "fit-content",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  pageContainer: {
    margin: "25px",
    width: "100%",
  },
  homePagePaper: {
    backgroundColor: "rgb(235, 235, 235)",
    padding: "25px",
    textAlign: "center",
    height: "fit-content",
  },
  managerPagePaper: {
    backgroundColor: "rgb(235, 235, 235)",
    padding: "25px",
    textAlign: "center",
    height: "fit-content",
  },
  bottomBar: {
    backgroundColor: "rgb(235, 235, 235)",
    display: "flex",
    width: "100%",
    height: "100px",
    margin: "0px",
    color: "black",
    borderRadius: "0%",
    position: "relative",
    boxShadow: "3px 0px 1px 1px rgba(0, 0, 0, 0.4)",
    textAlign: "left",
    alignItems: "center",
  },
  bottomBarText: {
    fontSize: "25px",
    paddingLeft: "20px",
    fontFamily: "Oswald, sans-serif",
    fontWeight: "bold",
  },
};
